### ISSUE TITLE
switching optimizers in mboost?

### ISSUE THREAD

**Issue by bachlaw** [boost-R/mboost#25]
This package is absolutely outstanding.  Thank you.

However, I have one model with a binary output that runs fine with glmer from the lme4 package, but gets hung up on a singular matrix in gamboost which cannot be inverted and thus solved.  Just generally speaking, I wonder if this may be a characteristic of the optimizer that is being used and if there is an option to switch to a different optimizer within mboost to see if it will address the problem.  

Thanks very much.

**Comment by hofnerb** [comment]
Sorry, @bachlaw. This isn't possible. Optimizers are base-learner specific and cannot be changed (if you do not re-implement the base-learner).

However, I think this error might already occur in `df2lambda()` (see [code](https://github.com/hofnerb/mboost/blob/master/pkg/mboostPatch/R/bl.R#L4)), the function with computes the penalty parameter `lambda` for given degrees of freedom `df` (or vice versa). Without a minimal example and / or the error message this error might be either due to wrong options / arguments in the model or a real issue.
