### ISSUE TITLE
RCG family missing

### ISSUE THREAD

**Issue by biobenkj** [boost-R/mboost#86]
I'm working on methylation array (EPIC) data analysis and would like to use the RCG method proposed in Weinhold et al 2016 (BMC Bioinformatics). However, it doesn't exist in the latest release (development branch) of mboost. It does exist in the package distributed with the manuscript. Could you clarify where this family method exists in the latest mboost or why it was dropped?

Thanks!

**Comment by hofnerb** [comment]
Sorry, I also don't know. The authors only provided the function on the BMC Bioinformatics page in a modified version of mboost. I will enquire, however, whether it would be acceptable to move the function to the official package. Please stay tuned :)

**Comment by biobenkj** [comment]
Thanks!

**Comment by hofnerb** [comment]
**Quick solution:** Use the package provided [here](https://static-content.springer.com/esm/art%3A10.1186%2Fs12859-016-1347-4/MediaObjects/12859_2016_1347_MOESM3_ESM.gz)

In the meantime, we are working on a patch in order to provide the functionality within mboost. This will take some time (I cannot say how much as it depends on the spare time of Weinhold et al).

**Comment by biobenkj** [comment]
Thanks for your time and will use v2.6.0 provided with the manuscript. Thanks for looking into this!
